title:             Lin's Blog :)
description:       This blog is a journal for Lin's 2 years at NYU, ITP and beyond.
permalink:         ':title/'
baseurl:           "/blog" # the subpath of your site, e.g. /blog
url:               "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:      #if your site has a twitter account, enter it here

# Author Settings
author:            Lin Zhang  # add your name
author-img:        lz.jpg # add your photo
about-author:      I am a graduate student and front-end developer. Just like Javascript, I am weird and awesome. # add description
#social-twitter:   # add your Twitter handle
#social-facebook:  # add your Facebook handle
social-github:     linzhangcs # add your Github handle
social-linkedin:   lin-zhang-7453b639 # add your Linkedin handle
social-email:      lz1414@nyu.edu # add your Email address

# Disqus
discus-identifier: linzhang # add your discus identifier

# Tracker
analytics:         # Google Analytics

# Build Settings
markdown:          kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
gems:
  - jemoji

paginate:          10
paginate_path:     "/page/:num"

exclude:           ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
